DROP DATABASE IF EXISTS a23marcoscc_BDExercicio1;
GO
CREATE DATABASE a23marcoscc_BDExercicio1;
GO
USE a23marcoscc_BDExercicio1;


CREATE TABLE EMPLEADO (

	codemp SMALLINT IDENTITY(2, 1) PRIMARY KEY,
	--CHECK

	nombre VARCHAR(30) NOT NULL,
	apellido1 VARCHAR(30) NOT NULL,
	apellido2 VARCHAR(30) NOT NULL,
	direccion VARCHAR(30),
	provincia VARCHAR(30) DEFAULT('Pontevedra'),
	--CHECK
	DNI CHAR(9),
	--CHECK
	coddepto SMALLINT ,
	--FOREIGN KEY
	salario SMALLMONEY DEFAULT(800),
	--CHECK
	fecalta CHAR(10),
	--CHECK
	dto DECIMAL(4,2),

);



CREATE TABLE DEPARTAMENTO (

	coddepto SMALLINT IDENTITY(2, 1) PRIMARY KEY,
	depto VARCHAR(30) NOT NULL,
	codjefe CHAR(2), 
	--FOREIGN KEY
	presupuesto SMALLMONEY DEFAULT(0),

);



CREATE TABLE HORAS_EXTRA (

	codemp SMALLINT IDENTITY(2, 1),
	--FOREIGN KEY
	--PRIMARY KEY
	fecha DATE,
	--PRIMARY KEY
	num_horas tinyint,

	CONSTRAINT PK_HORAS_EXTRA
	PRIMARY KEY (codemp, fecha),
);



-- CONDICIONES TABLA EMPLEADO

	--CHECK DNI
	ALTER TABLE EMPLEADO
		ADD CONSTRAINT CK_DNI 
		CHECK (DNI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Za-z]');


	--FOREIGN KEY
	ALTER TABLE EMPLEADO
		ADD CONSTRAINT FK_EMPLEADO_DEPARTAMENTO
		FOREIGN KEY(coddepto)
		REFERENCES DEPARTAMENTO(coddepto)
		ON UPDATE CASCADE ON DELETE CASCADE;


	--CHECK FECALTA
	ALTER TABLE EMPLEADO
		ADD CONSTRAINT CK_FECALTA
		CHECK (fecalta LIKE '[0-9][0-9]/[0-1][0-9]/[0-9][0-9][0-9][0-9]');



-- CONDICIONES TABLA DEPARTAMENTO

	--FOREIGN KEY
	ALTER TABLE DEPARTAMENTO
		ADD CONSTRAINT FK_DEPARTAMENTO_EMPLEADO
		FOREIGN KEY (codjefe)
		REFERENCES EMPLEADO(codemp)
		ON UPDATE CASCADE ON DELETE CASCADE;
