CREATE DATABASE a23marcoscc_Libreria

GO

USE a23marcoscc_Libreria;


CREATE TABLE AMIGO (

	Cod_Ami CHAR(4) PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL,
	Enderezo VARCHAR (30),
	Telefono VARCHAR(9) NOT NULL,
	Presta BIT NOT NULL,
	Regala BIT NOT NULL
	
);



CREATE TABLE LIBRERIA (

	Cod_Libreria CHAR(4) PRIMARY KEY,
	Nome VARCHAR (30) NOT NULL,
	Enderezo VARCHAR(30),
	Telefono VARCHAR(9) NOT NULL,
	Persoa_Cont CHAR(2) NOT NULL

);



CREATE TABLE EDITORIAL (

	Cod_Edi CHAR(4) PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL
	

);



CREATE TABLE LIBRO (

	Cod_Libro CHAR(4) PRIMARY KEY,
	Titulo VARCHAR(30) NOT NULL,
	Data_Adq DATE,
	Ano_Edi DATE,
	Cod_Edi CHAR(4) NOT NULL, -- FOREIGN KEY
	Prezo FLOAT,
	Fot_Ori BIT NOT NULL,
	Mer_Reg BIT NOT NULL,
	Esp_Can BIT,
	Cod_Ami CHAR(4), -- FOREIGN KEY
	Cod_Libreria CHAR(4), -- FOREIGN KEY
		

	CONSTRAINT FK_COD_EDI_LIBRO 
	FOREIGN KEY (Cod_Edi) 
	REFERENCES EDITORIAL(Cod_Edi) 
	ON UPDATE CASCADE ON DELETE NO ACTION,

	CONSTRAINT FEK_COD_AMI_LIBRO 
	FOREIGN KEY (Cod_Ami) 
	REFERENCES AMIGO(Cod_Ami) 
	ON UPDATE CASCADE ON DELETE NO ACTION,

	CONSTRAINT FEK_COD_LIBRERIA_LIBRO 
	FOREIGN KEY (Cod_Libreria)
	REFERENCES LIBRERIA (Cod_Libreria) 
	ON UPDATE CASCADE ON DELETE NO ACTION
);


CREATE TABLE AUTOR (

	Cod_Autor CHAR(4) PRIMARY KEY,
	Nome VARCHAR(30)NOT NULL,

);



CREATE TABLE LIBRO_AUTOR (

	Cod_Autor CHAR(4),
	Cod_Libro CHAR(4)
	
	CONSTRAINT PF_LIBRO_AUTOR 
	PRIMARY KEY (Cod_Autor, Cod_Libro),

	CONSTRAINT FK_COD_AUTOR_LIBRO_AUTOR 
	FOREIGN KEY (Cod_Autor) 
	REFERENCES AUTOR(Cod_Autor)
	ON UPDATE CASCADE ON DELETE NO ACTION,

	CONSTRAINT FK_COD_LIBRO_lIBRO_AUTOR 
	FOREIGN KEY (Cod_Libro) 
	REFERENCES LIBRO(Cod_Libro) 
	ON UPDATE CASCADE ON DELETE CASCADE

);



CREATE TABLE PRESTAMO (

	Cod_Ami_Pre CHAR (4),
	Cod_Libro CHAR(4),
	Data_Dev DATE
	
	
	CONSTRAINT PK_PRESTAMO 
	PRIMARY KEY (Cod_Ami_Pre,Cod_Libro)

	CONSTRAINT FK_COD_AMI_PRE_PRESTAMO 
	FOREIGN KEY (Cod_Ami_Pre) 
	REFERENCES AMIGO(Cod_Ami) 
	ON UPDATE CASCADE ON DELETE CASCADE,

	CONSTRAINT FK_COD_LIBRO_PRESTAMO 
	FOREIGN KEY (Cod_Libro) 
	REFERENCES LIBRO(Cod_Libro)
	ON UPDATE NO ACTION ON DELETE CASCADE
	

);



CREATE TABLE INDICE (

	Cod_Libro CHAR(4),
	Cod_Tit CHAR(4),
	Texto_tit VARCHAR(30) NOT NULL,
	Paxina INT NOT NULL,
	Cod_L_Pai CHAR(4),
	Cod_T_Pai CHAR(4)

	CONSTRAINT PK_INDICE 
	PRIMARY KEY (Cod_Libro, Cod_Tit),

	CONSTRAINT FK_COD_LIBRO_INDICE 
	FOREIGN KEY (Cod_Libro) 
	REFERENCES LIBRO (Cod_Libro) 
	ON UPDATE CASCADE ON DELETE CASCADE,

	CONSTRAINT FK_COD_L_PAI_COD_T_PAI_INDICE 
	FOREIGN KEY (Cod_L_Pai,Cod_T_Pai) 
	REFERENCES INDICE(Cod_Libro, Cod_Tit) 
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
