DROP DATABASE IF EXISTS a23marcoscc_Recuperacion;
GO
CREATE DATABASE a23marcoscc_Recuperacion;
GO
USE a23marcoscc_Recuperacion;

CREATE TABLE COMUNIDAD (

	Cod_Comu CHAR(2) PRIMARY KEY,
	Nombre VARCHAR(30),
	Extension smallint

);


CREATE TABLE LOCALIDAD (

	Cod_Loca CHAR(2) PRIMARY KEY,
	Nombre VARCHAR(30),
	Cod_Comu CHAR(2),

	CONSTRAINT FK_LOCALIDAD_COMUNIDAD
	FOREIGN KEY (Cod_Comu)
	REFERENCES COMUNIDAD(Cod_Comu)
	ON UPDATE CASCADE ON DELETE CASCADE,
);


CREATE TABLE COD_POST (

	Id_Cod_Post CHAR(2),
	Cod_Loca CHAR(2),
	Codigo CHAR(5)

	CONSTRAINT PK_COD_POST
	PRIMARY KEY (Id_Cod_Post,Cod_Loca)

	CONSTRAINT FK_COD_POST_LOCALIDAD
	FOREIGN KEY (Cod_Loca)
	REFERENCES LOCALIDAD(Cod_Loca)
	ON UPDATE CASCADE ON DELETE CASCADE,
);


CREATE TABLE ETAPA (

	Cod_Etapa CHAR(2) PRIMARY KEY,
	Km FLOAT,
	Tiempo FLOAT,
	Cod_Loca CHAR(2),

	CONSTRAINT FK_ETAPA_LOCALIDAD
	FOREIGN KEY (Cod_Loca)
	REFERENCES LOCALIDAD(Cod_Loca)
	ON UPDATE CASCADE ON DELETE CASCADE, 


);


CREATE TABLE CRUZA (

	Cod_Etapa CHAR(2),
	Cod_Loca CHAR(2),

    CONSTRAINT PK_CRUZA
    PRIMARY KEY (Cod_Etapa,Cod_Loca),

    CONSTRAINT FK_CRUZA_ETAPA
    FOREIGN KEY (Cod_Etapa)
    REFERENCES ETAPA(Cod_Etapa)
    ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT FK_CRUZA_LOCALIDAD
    FOREIGN KEY (Cod_Loca)
    REFERENCES LOCALIDAD(Cod_Loca)
    ON UPDATE CASCADE ON DELETE CASCADE,

);


CREATE TABLE CAMINO (

    Cod_Camino CHAR(2) PRIMARY KEY,
    Nombre VARCHAR(30),
    

);


CREATE TABLE CONTIENE (

    Cod_Etapa CHAR(2),
    Cod_Camino CHAR(2),

    CONSTRAINT PK_CONTIENE
    PRIMARY KEY (Cod_Etapa,Cod_Camino),

    CONSTRAINT FK_CONTIENE_ETAPA
    FOREIGN KEY (Cod_Etapa)
    REFERENCES ETAPA(Cod_Etapa)
    ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT FK_CONTIENE_CAMINO
    FOREIGN KEY (Cod_Camino)
    REFERENCES CAMINO(Cod_Camino)
    ON UPDATE CASCADE ON DELETE CASCADE,

);


CREATE TABLE PEREGRINO (

    Numero CHAR(2) PRIMARY KEY,
    DNI CHAR(9) CHECK (DNI LIKE '[0-9]{8}[A-Z]'),
    Nombre VARCHAR(30),
    Direccion VARCHAR(30),

);

CREATE TABLE Ciclistas (

    Numero CHAR(2) PRIMARY KEY,
    Pais_Ori VARCHAR(30),

    CONSTRAINT FK_CICLISTAS_PEREGRINO
    FOREIGN KEY (Numero)
    REFERENCES PEREGRINO(Numero)
    ON UPDATE CASCADE ON DELETE CASCADE,

);

CREATE TABLE ATRAVIESA (

    Fecha DATE,
    Cod_Loca CHAR(2),
    Numero CHAR(2),

    CONSTRAINT PK_ATRAVIESA
    PRIMARY KEY (Fecha,Cod_Loca,Numero),

    CONSTRAINT FK_ATRAVIESA_LOCALIDAD
    FOREIGN KEY (Cod_Loca)
    REFERENCES LOCALIDAD(Cod_Loca)
    ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT FK_ATRAVIESA_PEREGRINO
    FOREIGN KEY (Numero)
    REFERENCES PEREGRINO(Numero)
    ON UPDATE CASCADE ON DELETE CASCADE,

);

CREATE TABLE RECORRE (

    Cod_Camino CHAR(2),
    Numero CHAR(2),
    Estado CHAR(1) CHECK (Estado IN ('S','A')),

    CONSTRAINT PK_RECORRE
    PRIMARY KEY (Cod_Camino,Numero),

    CONSTRAINT FK_RECORRE_CAMINO
    FOREIGN KEY (Cod_Camino)
    REFERENCES CAMINO(Cod_Camino)
    ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT FK_RECORRE_PEREGRINO
    FOREIGN KEY (Numero)
    REFERENCES PEREGRINO(Numero)
    ON UPDATE CASCADE ON DELETE CASCADE,
);

CREATE TABLE ALBERGUE (

    Cod_Albergue CHAR(2) PRIMARY KEY,
    Nombre VARCHAR(30),
    Capacidad smallint,
    Cod_Loca CHAR(2),

    CONSTRAINT FK_ALBERGUE_LOCALIDAD
    FOREIGN KEY (Cod_Loca)

    REFERENCES LOCALIDAD(Cod_Loca)
    ON UPDATE CASCADE ON DELETE CASCADE,
    
);


CREATE TABLE PRIVADOS(

    Cod_Albergue CHAR(2) PRIMARY KEY,
    DNI_Dueño CHAR(9) CHECK (DNI_Dueño LIKE '[0-9]{8}[A-Z]'),

    CONSTRAINT FK_PRIVADOS_ALBERGUE
    FOREIGN KEY (Cod_Albergue)
    REFERENCES ALBERGUE(Cod_Albergue)
    ON UPDATE CASCADE ON DELETE CASCADE,

);

CREATE TABLE PRECIO(

    Fecha DATE,
    Cod_Albergue CHAR(2),
    Precio SMALLMONEY,


    CONSTRAINT PK_PRECIO
    PRIMARY KEY (Cod_Albergue,Fecha),

    CONSTRAINT FK_PRECIO_ALBERGUE
    FOREIGN KEY (Cod_Albergue)
    REFERENCES ALBERGUE(Cod_Albergue)
    ON UPDATE CASCADE ON DELETE CASCADE,

);

CREATE TABLE EDIFICIOS(

    Cod_Edificio CHAR(2),
    Nombre VARCHAR(30),
    Tamaño SMALLINT,
    Capacidad SMALLINT,
    Cod_Albergue CHAR(2),

    CONSTRAINT PK_EDIFICIOS
    PRIMARY KEY (Cod_Edificio),

    CONSTRAINT FK_EDIFICIOS_ALBERGUE
    FOREIGN KEY (Cod_Albergue)
    REFERENCES ALBERGUE(Cod_Albergue)
    ON UPDATE CASCADE ON DELETE CASCADE,  
    
);


CREATE TABLE ORG_PATRO(

    Cod_ORG CHAR(2) PRIMARY KEY,
    Nom_ORG VARCHAR(30),
    Ambito VARCHAR(30),

)

CREATE TABLE PUBLICO(
    Cod_Albergue CHAR(2),
    Patrocinio CHAR(1) CHECK (Patrocinio IN ('T','P')),
    Cod_Org CHAR(2),

    CONSTRAINT PK_PUBLICO
    PRIMARY KEY (Cod_Albergue),

    CONSTRAINT FK_PUBLICO_ALBERGUE
    FOREIGN KEY (Cod_Albergue)
    REFERENCES ALBERGUE(Cod_Albergue)
    ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT FK_PUBLICO_ORG
    FOREIGN KEY (Cod_Org)
    REFERENCES ORG_PATRO(Cod_ORG)
    ON UPDATE CASCADE ON DELETE CASCADE,
)